#!/bin/sh

#SBATCH --job-name eda_sim
#SBATCH --partition common
#SBATCH --account gelfandlab
#SBATCH --mail-type ALL
#SBATCH --mail-user joshua.hewitt@duke.edu
#SBATCH --ntasks 1
#SBATCH --array=1-400

module unload R
module load R/3.5.2

date
START=`date +%s`
R --no-save --no-restore CMD BATCH Rscripts/sim/sim.R ${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.Rout
END=`date +%s`
date

ELAPSED=$(( $END - $START ))
echo "Elapsed time (hrs): $(echo "scale=10; $ELAPSED/3600" | bc)"